---
apiVersion: hub.traefik.io/v1alpha1
kind: API
metadata:
  name: licensed-api
  namespace: apps
  labels:
    subscription: standard
spec:
  pathPrefix: "/weather/licensed"
  service:
    name: private-app
    port:
      number: 3000
    openApiSpec:
      path: /openapi.yaml

---
apiVersion: hub.traefik.io/v1alpha1
kind: API
metadata:
  name: admin-api
  namespace: admin
spec:
  pathPrefix: "/admin"
  service:
    name: admin-app
    port:
      number: 3000
