---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules
  namespace: monitoring
data:
  general.yaml: |

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-core
  namespace: monitoring
data:
  prometheus.yaml: |
    global:
      scrape_interval: 10s
      scrape_timeout: 10s
      evaluation_interval: 10s

    # Prom is deployed statically, not through the Prom Operator, so instead of using a ServiceMonitor or an annotation, we add the jobs here
    # @see: https://www.infracloud.io/blogs/prometheus-operator-helm-guide/#how-does-prometheus-find-all-the-targets-to-monitor-and-scrape
    scrape_configs:
      # Scrape prometheus itself, the job name is added as a label `job=<job_name>` to any timeseries scraped from this config
      - job_name: 'prometheus'
        # metrics_path defaults to '/metrics'
        # scheme defaults to 'http'.
        static_configs:
          - targets: ['localhost:9090']
      - job_name: 'flux-system'
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            target_label: __address__
          - source_labels: [__meta_kubernetes_pod_label_app]
            action: replace
            replacement: $1
            target_label: app
          - target_label: namespace
            source_labels: [__meta_kubernetes_namespace]
          - target_label: pod
            source_labels: [__meta_kubernetes_pod_name]
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - flux-system
