---
apiVersion: v1
kind: Namespace
metadata:
  name: admin

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: admin-data
  namespace: admin
data:
  api.json: |
    {
      "settings": [
        { "id": 1, "lang": "en" },
        { "id": 2, "lang": "fr" },
      ]
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-app
  namespace: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-app
  template:
    metadata:
      labels:
        app: admin-app
    spec:
      containers:
        - name: api
          image: ghcr.io/traefik-workshops/api-server:v0.1.0
          args: ["-data", "/api/api.json", "-errorrate", "0"]
          imagePullPolicy: Always
          volumeMounts:
          - name: api-data
            mountPath: /api
      volumes:
        - name: api-data
          configMap:
            name: admin-data

---
apiVersion: v1
kind: Service
metadata:
  name: admin-app
  namespace: admin
  labels:
    app: admin-app
spec:
  type: ClusterIP
  ports:
    - port: 3000
      name: api
  selector:
    app: admin-app

