---
apiVersion: v1
kind: Namespace
metadata:
  name: apps

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: private-app-data
  namespace: apps
data:
  api.json: |
    {
      "forecast": [
        { "id": 1, "city": "GopherCity", "weather": "Cloudy", "dt": "3128231402" },
        { "id": 2, "city": "City of Gopher", "weather": "Rainy", "dt": "3128231402" },
        { "id": 3, "code": "GopherCentral", "weather": "Shiny", "dt": "3128231402" }
      ]
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: private-app
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: private-app
  template:
    metadata:
      labels:
        app: private-app
    spec:
      containers:
        - name: api
          image: ghcr.io/traefik-workshops/api-server:v0.1.0
          args: ["-data", "/api/api.json", "-openapi", "/public/openapi.yaml", "-errorrate", "2"]
          imagePullPolicy: Always
          volumeMounts:
          - name: api-data
            mountPath: /api
          - name: openapi
            mountPath: /public
      volumes:
        - name: api-data
          configMap:
            name: private-app-data
        - name: openapi
          configMap:
            name: private-app-openapispec

---
apiVersion: v1
kind: Service
metadata:
  name: private-app
  namespace: apps
  labels:
    app: private-app
spec:
  type: ClusterIP
  ports:
    - port: 3000
      name: api
  selector:
    app: private-app

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: private-app-openapispec
  namespace: apps
data:
  openapi.yaml: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: Forecast Weather
      description: Forecast Weather API
      contact:
        name: TraefikLabs
        url: 'https://traefik.io/'
      license:
        name: Apache 2.0
        url: 'https://spdx.org/licenses/Apache-2.0.html'
    tags:
      - name: external
        description: routes exposed publicly
      - name: internal
        description: routes reserved for internal usage
    paths:
      /forecast:
        get:
          summary: Retrieve weather
          operationId: getForecast
          tags:
            - external
          parameters:
            - name: city
              in: query
              description: City
              required: true
              schema:
                type: string
          responses:
            '200':
              description: An array of forecasted weathers
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/weathers"
            '204':
              $ref: '#/components/responses/nocontent'
            '401':
              $ref: '#/components/responses/unauthorized'
            '500':
              $ref: '#/components/responses/serverError'
        patch:
          summary: Update weather data
          operationId: patchForecast
          tags:
            - external
          parameters:
            - name: city
              in: query
              description: City
              required: true
              schema:
                type: string
          responses:
            '200':
              description: An array of forecasted weathers
              content:
                application/json:
                  schema:
                    $ref: "#/components/schemas/weathers"
            '204':
              $ref: '#/components/responses/nocontent'
            '401':
              $ref: '#/components/responses/unauthorized'
            '500':
              $ref: '#/components/responses/serverError'

    components:
      responses:
        nocontent:
          description: "No content"
        unauthorized:
          description: "Access token is missing or invalid"
        serverError:
          description: "Internal server error"
      schemas:
        weather:
          type: object
          required:
            - id
            - name
          properties:
            id:
              type: integer
              format: int64
            city:
              type: string
            weather:
              type: string
            dt:
              type: string
        weathers:
          type: array
          maxItems: 100
          items:
            $ref: "#/components/schemas/weather"
      securitySchemes:
        bearerAuth:
          description: "Bearer Auth"
          type: http
          scheme: bearer
          bearerFormat: JWT
