---
apiVersion: v1
kind: Namespace
metadata:
  name: apps

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: public-data
  namespace: apps
data:
  api.json: |
    {
      "public": [
        { "id": 1, "city": "GopherCity", "weather": "Moderate rain" },
        { "id": 2, "city": "City of Gophers", "weather": "Sunny" },
        { "id": 3, "city": "GopherRocks", "weather": "Cloudy" }
      ]
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: public-app
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: public-app
  template:
    metadata:
      labels:
        app: public-app
    spec:
      containers:
        - name: api
          image: ghcr.io/traefik-workshops/api-server:v0.1.0
          args: ["-data", "/api/api.json", "-errorrate", "2"]
          imagePullPolicy: Always
          volumeMounts:
          - name: api-data
            mountPath: /api
      volumes:
        - name: api-data
          configMap:
            name: public-data

---
apiVersion: v1
kind: Service
metadata:
  name: public-app
  namespace: apps
  labels:
    app: public-app
spec:
  type: ClusterIP
  ports:
    - port: 3000
      name: api
  selector:
    app: public-app
