---
apiVersion: v1
kind: Namespace
metadata:
  name: hydra
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hydra
  namespace: hydra
  labels:
    app: hydra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hydra
  template:
    metadata:
      labels:
        app: hydra
    spec:
      automountServiceAccountToken: false
      containers:
        - name: hydra
          image: docker.io/oryd/hydra:v2.1.2
          args:
            - serve
            - all
            - --dangerous-force-http
          env:
            - name: URLS_SELF_ISSUER
              value: http://hydra.hydra.svc.cluster.local:4444
            - name: URLS_SELF_PUBLIC
              value: http://hydra.docker.localhost
            - name: URLS_SELF_ADMIN
              value: http://hydra.hydra.svc.cluster.local:4445
            # Login and consent is proxied to hub-api-management
            - name: URLS_LOGIN
              value: http://consent.hydra.svc.cluster.local:3000/login
            - name: URLS_CONSENT
              value: http://consent.hydra.svc.cluster.local:3000/consent
            - name: URLS_LOGOUT
              value: http://consent.hydra.svc.cluster.local:3000/logout
            - name: DSN
              value: memory
            - name: SECRETS_SYSTEM
              value: youReallyNeedToChangeThis
            - name: OIDC_SUBJECT_IDENTIFIERS_SUPPORTED_TYPES
              value: public,pairwise
            - name: OIDC_SUBJECT_IDENTIFIERS_PAIRWISE_SALT
              value: youReallyNeedToChangeThis
            - name: STRATEGIES_ACCESS_TOKEN
              value: jwt
          ports:
            - containerPort: 4444
              name: public
              protocol: TCP
            - containerPort: 4445
              name: admin
              protocol: TCP
            - containerPort: 5555
              name: token # Port for hydra token user
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health/alive
              port: 4445
              httpHeaders:
                - name: Host
                  value: "127.0.0.1"
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 4445
              httpHeaders:
                - name: Host
                  value: "127.0.0.1"
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 5
          startupProbe:
            httpGet:
              path: /health/ready
              port: 4445
              httpHeaders:
                - name: Host
                  value: "127.0.0.1"
            failureThreshold: 60
            successThreshold: 1
            periodSeconds: 1
            timeoutSeconds: 1
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65534
            runAsGroup: 65534
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consent
  namespace: hydra
  labels:
    app: hail-hydra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hail-hydra
  template:
    metadata:
      labels:
        app: hail-hydra
    spec:
      automountServiceAccountToken: false
      containers:
        - name: hydra
          image: jlevesy/hail-hydra:v0.0.1
          args:
            - -a
            - http://hydra.hydra.svc.cluster.local:4445
            - -b :3000
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: hydra
  namespace: hydra
  labels:
    app: hydra
spec:
  type: ClusterIP
  ports:
    - port: 4444
      targetPort: public
      name: public
    - port: 4445
      targetPort: admin
      name: admin
    - port: 5555
      targetPort: token
      name: token
  selector:
    app: hydra
---
apiVersion: v1
kind: Service
metadata:
  name: consent
  namespace: hydra
  labels:
    app: hail-hydra
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: http
      name: http
  selector:
    app: hail-hydra
